const livros = [
    {   
        "nome": "Talvez você deva conversar com alguém",
        "autor": "Lori Gottlieb",
        "categoria": "Psicologia",
        "paginas": 448,
        "recomenda": "True",
        "leu": "True",
    },
    {
        "nome": "Mulheres que correm com os lobos",
        "autor": "Clarissa Pinkola Estés",
        "categoria": "Psicanálise",
        "paginas": 576,
        "recomenda": "True",
        "leu": "True",
    },
    {
        "nome": "O que o sol faz com as flores",
        "autor": "Rupi Kaur",
        "categoria": "Poesia",
        "paginas": 256,
        "recomenda": "True",
        "leu": "True",
    },
    {
        "nome": "A amiga genial",
        "autor": "Elena Ferrante",
        "categoria": "Ficção contemporânea",
        "paginas": 336,
        "recomenda": "True",
        "leu": "True",
    },
    {
        "nome": "Torto Arado",
        "autor": "Itamar Vieira Jr",
        "categoria": "Drama",
        "paginas": 264,
        "recomenda": "False",
        "leu": "False",
    },
    {
        "nome": "O curso do amor",
        "autor": "Alain de Botton",
        "categoria": "Auto ajuda",
        "paginas": 209,
        "recomenda": "False",
        "leu": "False",
    },
    {
        "nome": "Indomável",
        "autor": "Glennon Doyle",
        "categoria": "Transformação pessoal",
        "paginas": 320,
        "recomenda": "False",
        "leu": "False",
    },
    {
        "nome": "Pequeno manual antiracista",
        "autor": "Djamila Ribeiro",
        "categoria": "Social",
        "paginas": 136,
        "recomenda": "True",
        "leu": "True",
    },
    {
        "nome": "A sutil arte de ligar o foda-se",
        "autor": "Mark Manson",
        "categoria": "Tranformação pessoal",
        "paginas": 224,
        "recomenda": "False",
        "leu": "True",
    },
    {
        "nome": "Frida",
        "autor": "Hayden Herrera",
        "categoria": "Biografia",
        "paginas": 624,
        "recomenda": "True",
        "leu": "True", 
    }

]

module.exports = livros